name: DarkBits
version: 'DEV-1.0.1'
main: sk.adr3ez.darkbits.DarkBits
api-version: 1.18
softdepend: [ PlaceholderAPI ]
authors: [ Adr3ez_ ]
commands:
  bits:
    description: Default command to plugin
